package com.mce.models.blocks;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class SuperReactorModel extends ModelBase {
	// fields
	ModelRenderer Base_Bottom_1;
	ModelRenderer Base_Bottom_2;
	ModelRenderer Base_Bottom_3;
	ModelRenderer Base_Top_1;
	ModelRenderer Base_Top_2;
	ModelRenderer Base_Top_3;
	ModelRenderer U_Inner_Core_1;
	ModelRenderer U_Inner_Core_2;
	ModelRenderer Es_Inner_Core_1;
	ModelRenderer Es_Inner_Core_2;
	ModelRenderer Np_Inner_Core_1;
	ModelRenderer Np_Inner_Core_2;
	ModelRenderer Holding_Inner_Core;
	ModelRenderer Housing_Support_1;
	ModelRenderer Housing_Support_2;
	ModelRenderer Housing_Support_3;
	ModelRenderer Housing_Support_4;
	ModelRenderer Side_Pannel_1;
	ModelRenderer Side_Pannel_2;
	ModelRenderer Side_Pannel_3;
	ModelRenderer Side_Pannel_4;
	ModelRenderer Upper_Side_Pannel_Support_1;
	ModelRenderer Upper_Side_Pannel_Support_2;
	ModelRenderer Upper_Side_Pannel_Support_3;
	ModelRenderer Upper_Side_Pannel_Support_4;
	ModelRenderer Lower_Side_Pannel_Support_1;
	ModelRenderer Lower_Side_Pannel_Support_2;
	ModelRenderer Lower_Side_Pannel_Support_3;
	ModelRenderer Lower_Side_Pannel_Support_4;
	ModelRenderer Transfer_Line_1;
	ModelRenderer Transfer_Line_2;
	ModelRenderer Transfer_Line_3;
	ModelRenderer Transfer_Line_4;

	public SuperReactorModel() {
		textureWidth = 128;
		textureHeight = 128;

		Base_Bottom_1 = new ModelRenderer(this, 0, 0);
		Base_Bottom_1.addBox(0F, 0F, 0F, 16, 1, 16);
		Base_Bottom_1.setRotationPoint(-8F, 23F, -8F);
		Base_Bottom_1.setTextureSize(128, 128);
		Base_Bottom_1.mirror = true;
		setRotation(Base_Bottom_1, 0F, 0F, 0F);
		Base_Bottom_2 = new ModelRenderer(this, 41, 18);
		Base_Bottom_2.addBox(0F, 0F, 0F, 14, 1, 14);
		Base_Bottom_2.setRotationPoint(-7F, 22F, -7F);
		Base_Bottom_2.setTextureSize(128, 128);
		Base_Bottom_2.mirror = true;
		setRotation(Base_Bottom_2, 0F, 0F, 0F);
		Base_Bottom_3 = new ModelRenderer(this, 65, 0);
		Base_Bottom_3.addBox(0F, 0F, 0F, 10, 1, 10);
		Base_Bottom_3.setRotationPoint(-5F, 21F, -5F);
		Base_Bottom_3.setTextureSize(128, 128);
		Base_Bottom_3.mirror = true;
		setRotation(Base_Bottom_3, 0F, 0F, 0F);
		Base_Top_1 = new ModelRenderer(this, 0, 0);
		Base_Top_1.addBox(0F, 0F, 0F, 16, 1, 16);
		Base_Top_1.setRotationPoint(-8F, 8F, -8F);
		Base_Top_1.setTextureSize(128, 128);
		Base_Top_1.mirror = true;
		setRotation(Base_Top_1, 0F, 0F, 0F);
		Base_Top_2 = new ModelRenderer(this, 41, 18);
		Base_Top_2.addBox(0F, 0F, 0F, 14, 1, 14);
		Base_Top_2.setRotationPoint(-7F, 9F, -7F);
		Base_Top_2.setTextureSize(128, 128);
		Base_Top_2.mirror = true;
		setRotation(Base_Top_2, 0F, 0F, 0F);
		Base_Top_3 = new ModelRenderer(this, 65, 0);
		Base_Top_3.addBox(0F, 0F, 0F, 10, 1, 10);
		Base_Top_3.setRotationPoint(-5F, 10F, -5F);
		Base_Top_3.setTextureSize(128, 128);
		Base_Top_3.mirror = true;
		setRotation(Base_Top_3, 0F, 0F, 0F);
		U_Inner_Core_1 = new ModelRenderer(this, 0, 18);
		U_Inner_Core_1.addBox(0F, 0F, 0F, 2, 10, 2);
		U_Inner_Core_1.setRotationPoint(-1F, 11F, 1F);
		U_Inner_Core_1.setTextureSize(128, 128);
		U_Inner_Core_1.mirror = true;
		setRotation(U_Inner_Core_1, 0F, 0F, 0F);
		U_Inner_Core_2 = new ModelRenderer(this, 0, 18);
		U_Inner_Core_2.addBox(0F, 0F, 0F, 2, 10, 2);
		U_Inner_Core_2.setRotationPoint(-1.45F, 11F, 2F);
		U_Inner_Core_2.setTextureSize(128, 128);
		U_Inner_Core_2.mirror = true;
		setRotation(U_Inner_Core_2, 0F, 0.7853982F, 0F);
		Es_Inner_Core_1 = new ModelRenderer(this, 0, 45);
		Es_Inner_Core_1.addBox(0F, 0F, 0F, 2, 10, 2);
		Es_Inner_Core_1.setRotationPoint(-3F, 11F, -3F);
		Es_Inner_Core_1.setTextureSize(128, 128);
		Es_Inner_Core_1.mirror = true;
		setRotation(Es_Inner_Core_1, 0F, 0F, 0F);
		Es_Inner_Core_2 = new ModelRenderer(this, 0, 45);
		Es_Inner_Core_2.addBox(0F, 0F, 0F, 2, 10, 2);
		Es_Inner_Core_2.setRotationPoint(-3.45F, 11F, -2F);
		Es_Inner_Core_2.setTextureSize(128, 128);
		Es_Inner_Core_2.mirror = true;
		setRotation(Es_Inner_Core_2, 0F, 0.7853982F, 0F);
		Np_Inner_Core_1 = new ModelRenderer(this, 50, 45);
		Np_Inner_Core_1.addBox(0F, 0F, 0F, 2, 10, 2);
		Np_Inner_Core_1.setRotationPoint(1F, 11F, -3F);
		Np_Inner_Core_1.setTextureSize(128, 128);
		Np_Inner_Core_1.mirror = true;
		setRotation(Np_Inner_Core_1, 0F, 0F, 0F);
		Np_Inner_Core_2 = new ModelRenderer(this, 50, 45);
		Np_Inner_Core_2.addBox(0F, 0F, 0F, 2, 10, 2);
		Np_Inner_Core_2.setRotationPoint(0.55F, 11F, -2F);
		Np_Inner_Core_2.setTextureSize(128, 128);
		Np_Inner_Core_2.mirror = true;
		setRotation(Np_Inner_Core_2, 0F, 0.7853982F, 0F);
		Holding_Inner_Core = new ModelRenderer(this, 9, 45);
		Holding_Inner_Core.addBox(0F, 0F, 0F, 10, 4, 10);
		Holding_Inner_Core.setRotationPoint(-5F, 14F, -5F);
		Holding_Inner_Core.setTextureSize(128, 128);
		Holding_Inner_Core.mirror = true;
		setRotation(Holding_Inner_Core, 0F, 0F, 0F);
		Housing_Support_1 = new ModelRenderer(this, 0, 31);
		Housing_Support_1.addBox(0F, 0F, 0F, 1, 10, 1);
		Housing_Support_1.setRotationPoint(3.7F, 11F, 3.7F);
		Housing_Support_1.setTextureSize(128, 128);
		Housing_Support_1.mirror = true;
		setRotation(Housing_Support_1, 0F, 0F, 0F);
		Housing_Support_2 = new ModelRenderer(this, 0, 31);
		Housing_Support_2.addBox(0F, 0F, 0F, 1, 10, 1);
		Housing_Support_2.setRotationPoint(-4.666667F, 11F, 3.7F);
		Housing_Support_2.setTextureSize(128, 128);
		Housing_Support_2.mirror = true;
		setRotation(Housing_Support_2, 0F, 0F, 0F);
		Housing_Support_3 = new ModelRenderer(this, 0, 31);
		Housing_Support_3.addBox(0F, 0F, 0F, 1, 10, 1);
		Housing_Support_3.setRotationPoint(3.7F, 11F, -4.7F);
		Housing_Support_3.setTextureSize(128, 128);
		Housing_Support_3.mirror = true;
		setRotation(Housing_Support_3, 0F, 0F, 0F);
		Housing_Support_4 = new ModelRenderer(this, 0, 31);
		Housing_Support_4.addBox(0F, 0F, 0F, 1, 10, 1);
		Housing_Support_4.setRotationPoint(-4.7F, 11F, -4.7F);
		Housing_Support_4.setTextureSize(128, 128);
		Housing_Support_4.mirror = true;
		setRotation(Housing_Support_4, 0F, 0F, 0F);
		Side_Pannel_1 = new ModelRenderer(this, 5, 31);
		Side_Pannel_1.addBox(0F, 0F, 0F, 1, 6, 6);
		Side_Pannel_1.setRotationPoint(7F, 13F, -3F);
		Side_Pannel_1.setTextureSize(128, 128);
		Side_Pannel_1.mirror = true;
		setRotation(Side_Pannel_1, 0F, 0F, 0F);
		Side_Pannel_2 = new ModelRenderer(this, 5, 31);
		Side_Pannel_2.addBox(0F, 0F, 0F, 6, 6, 1);
		Side_Pannel_2.setRotationPoint(-3F, 13F, 7F);
		Side_Pannel_2.setTextureSize(128, 128);
		Side_Pannel_2.mirror = true;
		setRotation(Side_Pannel_2, 0F, 0F, 0F);
		Side_Pannel_3 = new ModelRenderer(this, 5, 31);
		Side_Pannel_3.addBox(0F, 0F, 0F, 1, 6, 6);
		Side_Pannel_3.setRotationPoint(-8F, 13F, -3F);
		Side_Pannel_3.setTextureSize(128, 128);
		Side_Pannel_3.mirror = true;
		setRotation(Side_Pannel_3, 0F, 0F, 0F);
		Side_Pannel_4 = new ModelRenderer(this, 5, 31);
		Side_Pannel_4.addBox(0F, 0F, 0F, 6, 6, 1);
		Side_Pannel_4.setRotationPoint(-3F, 13F, -8F);
		Side_Pannel_4.setTextureSize(128, 128);
		Side_Pannel_4.mirror = true;
		setRotation(Side_Pannel_4, 0F, 0F, 0F);
		Upper_Side_Pannel_Support_1 = new ModelRenderer(this, 34, 18);
		Upper_Side_Pannel_Support_1.addBox(0F, 0F, 0F, 2, 5, 1);
		Upper_Side_Pannel_Support_1.setRotationPoint(-1F, 9F, 5F);
		Upper_Side_Pannel_Support_1.setTextureSize(128, 128);
		Upper_Side_Pannel_Support_1.mirror = true;
		setRotation(Upper_Side_Pannel_Support_1, 0.418879F, 0F, 0F);
		Upper_Side_Pannel_Support_2 = new ModelRenderer(this, 34, 18);
		Upper_Side_Pannel_Support_2.addBox(0F, 0F, 0F, 2, 5, 1);
		Upper_Side_Pannel_Support_2.setRotationPoint(-5F, 9F, -1F);
		Upper_Side_Pannel_Support_2.setTextureSize(128, 128);
		Upper_Side_Pannel_Support_2.mirror = true;
		setRotation(Upper_Side_Pannel_Support_2, 0.418879F, -1.570796F, 0F);
		Upper_Side_Pannel_Support_3 = new ModelRenderer(this, 34, 18);
		Upper_Side_Pannel_Support_3.addBox(0F, 0F, 0F, 2, 5, 1);
		Upper_Side_Pannel_Support_3.setRotationPoint(1F, 9F, -5F);
		Upper_Side_Pannel_Support_3.setTextureSize(128, 128);
		Upper_Side_Pannel_Support_3.mirror = true;
		setRotation(Upper_Side_Pannel_Support_3, 0.418879F, 3.141593F, 0F);
		Upper_Side_Pannel_Support_4 = new ModelRenderer(this, 34, 18);
		Upper_Side_Pannel_Support_4.addBox(0F, 0F, 0F, 2, 5, 1);
		Upper_Side_Pannel_Support_4.setRotationPoint(5F, 9F, 1F);
		Upper_Side_Pannel_Support_4.setTextureSize(128, 128);
		Upper_Side_Pannel_Support_4.mirror = true;
		setRotation(Upper_Side_Pannel_Support_4, 0.418879F, 1.570796F, 0F);
		Lower_Side_Pannel_Support_1 = new ModelRenderer(this, 34, 18);
		Lower_Side_Pannel_Support_1.addBox(0F, 0F, 0F, 2, 5, 1);
		Lower_Side_Pannel_Support_1.setRotationPoint(-1F, 23F, -5F);
		Lower_Side_Pannel_Support_1.setTextureSize(128, 128);
		Lower_Side_Pannel_Support_1.mirror = true;
		setRotation(Lower_Side_Pannel_Support_1, 0.418879F, 3.141593F,
				3.141593F);
		Lower_Side_Pannel_Support_2 = new ModelRenderer(this, 34, 18);
		Lower_Side_Pannel_Support_2.addBox(0F, 0F, 0F, 2, 5, 1);
		Lower_Side_Pannel_Support_2.setRotationPoint(-5F, 23F, 1F);
		Lower_Side_Pannel_Support_2.setTextureSize(128, 128);
		Lower_Side_Pannel_Support_2.mirror = true;
		setRotation(Lower_Side_Pannel_Support_2, 0.418879F, 1.570796F,
				3.141593F);
		Lower_Side_Pannel_Support_3 = new ModelRenderer(this, 34, 18);
		Lower_Side_Pannel_Support_3.addBox(0F, 0F, 0F, 2, 5, 1);
		Lower_Side_Pannel_Support_3.setRotationPoint(1F, 23F, 5F);
		Lower_Side_Pannel_Support_3.setTextureSize(128, 128);
		Lower_Side_Pannel_Support_3.mirror = true;
		setRotation(Lower_Side_Pannel_Support_3, 0.418879F, 0F, 3.141593F);
		Lower_Side_Pannel_Support_4 = new ModelRenderer(this, 34, 18);
		Lower_Side_Pannel_Support_4.addBox(0F, 0F, 0F, 2, 5, 1);
		Lower_Side_Pannel_Support_4.setRotationPoint(5F, 23F, -1F);
		Lower_Side_Pannel_Support_4.setTextureSize(128, 128);
		Lower_Side_Pannel_Support_4.mirror = true;
		setRotation(Lower_Side_Pannel_Support_4, 0.418879F, -1.570796F,
				3.141593F);
		Transfer_Line_1 = new ModelRenderer(this, 20, 31);
		Transfer_Line_1.addBox(0F, 0F, 0F, 2, 2, 2);
		Transfer_Line_1.setRotationPoint(-1F, 15F, -7F);
		Transfer_Line_1.setTextureSize(128, 128);
		Transfer_Line_1.mirror = true;
		setRotation(Transfer_Line_1, 0F, 0F, 0F);
		Transfer_Line_2 = new ModelRenderer(this, 20, 31);
		Transfer_Line_2.addBox(0F, 0F, 0F, 2, 2, 2);
		Transfer_Line_2.setRotationPoint(5F, 15F, -1F);
		Transfer_Line_2.setTextureSize(128, 128);
		Transfer_Line_2.mirror = true;
		setRotation(Transfer_Line_2, 0F, 0F, 0F);
		Transfer_Line_3 = new ModelRenderer(this, 20, 31);
		Transfer_Line_3.addBox(0F, 0F, 0F, 2, 2, 2);
		Transfer_Line_3.setRotationPoint(-7F, 15F, -1F);
		Transfer_Line_3.setTextureSize(128, 128);
		Transfer_Line_3.mirror = true;
		setRotation(Transfer_Line_3, 0F, 0F, 0F);
		Transfer_Line_4 = new ModelRenderer(this, 20, 31);
		Transfer_Line_4.addBox(0F, 0F, 0F, 2, 2, 2);
		Transfer_Line_4.setRotationPoint(-1F, 15F, 5F);
		Transfer_Line_4.setTextureSize(128, 128);
		Transfer_Line_4.mirror = true;
		setRotation(Transfer_Line_4, 0F, 0F, 0F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3,
			float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		Base_Bottom_1.render(f5);
		Base_Bottom_2.render(f5);
		Base_Bottom_3.render(f5);
		Base_Top_1.render(f5);
		Base_Top_2.render(f5);
		Base_Top_3.render(f5);
		U_Inner_Core_1.render(f5);
		U_Inner_Core_2.render(f5);
		Es_Inner_Core_1.render(f5);
		Es_Inner_Core_2.render(f5);
		Np_Inner_Core_1.render(f5);
		Np_Inner_Core_2.render(f5);
		Holding_Inner_Core.render(f5);
		Housing_Support_1.render(f5);
		Housing_Support_2.render(f5);
		Housing_Support_3.render(f5);
		Housing_Support_4.render(f5);
		Side_Pannel_1.render(f5);
		Side_Pannel_2.render(f5);
		Side_Pannel_3.render(f5);
		Side_Pannel_4.render(f5);
		Upper_Side_Pannel_Support_1.render(f5);
		Upper_Side_Pannel_Support_2.render(f5);
		Upper_Side_Pannel_Support_3.render(f5);
		Upper_Side_Pannel_Support_4.render(f5);
		Lower_Side_Pannel_Support_1.render(f5);
		Lower_Side_Pannel_Support_2.render(f5);
		Lower_Side_Pannel_Support_3.render(f5);
		Lower_Side_Pannel_Support_4.render(f5);
		Transfer_Line_1.render(f5);
		Transfer_Line_2.render(f5);
		Transfer_Line_3.render(f5);
		Transfer_Line_4.render(f5);
	}

	public void renderModel(float f5) {
		Base_Bottom_1.render(f5);
		Base_Bottom_2.render(f5);
		Base_Bottom_3.render(f5);
		Base_Top_1.render(f5);
		Base_Top_2.render(f5);
		Base_Top_3.render(f5);
		U_Inner_Core_1.render(f5);
		U_Inner_Core_2.render(f5);
		Es_Inner_Core_1.render(f5);
		Es_Inner_Core_2.render(f5);
		Np_Inner_Core_1.render(f5);
		Np_Inner_Core_2.render(f5);
		Holding_Inner_Core.render(f5);
		Housing_Support_1.render(f5);
		Housing_Support_2.render(f5);
		Housing_Support_3.render(f5);
		Housing_Support_4.render(f5);
		Side_Pannel_1.render(f5);
		Side_Pannel_2.render(f5);
		Side_Pannel_3.render(f5);
		Side_Pannel_4.render(f5);
		Upper_Side_Pannel_Support_1.render(f5);
		Upper_Side_Pannel_Support_2.render(f5);
		Upper_Side_Pannel_Support_3.render(f5);
		Upper_Side_Pannel_Support_4.render(f5);
		Lower_Side_Pannel_Support_1.render(f5);
		Lower_Side_Pannel_Support_2.render(f5);
		Lower_Side_Pannel_Support_3.render(f5);
		Lower_Side_Pannel_Support_4.render(f5);
		Transfer_Line_1.render(f5);
		Transfer_Line_2.render(f5);
		Transfer_Line_3.render(f5);
		Transfer_Line_4.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float f, float f1, float f2, float f3,
			float f4, float f5, Entity entity) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	}

}
